# Generated by Django 5.0 on 2024-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emailadress',
            field=models.EmailField(max_length=254),
        ),
    ]
