# Generated by Django 5.0 on 2024-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0002_alter_email_emailadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emailadress',
            field=models.CharField(max_length=200),
        ),
    ]
