# Generated by Django 5.0 on 2024-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0003_alter_email_emailadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emailadress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
